# Generated by Django 3.0.2 on 2020-03-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boughted_books_counter',
            field=models.IntegerField(default=0, verbose_name='counter'),
        ),
    ]
