# Generated by Django 3.0.2 on 2020-03-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0002_profile_boughted_books_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boughted_books',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
