# Generated by Django 3.0.2 on 2020-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0003_profile_boughted_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='boughted_books_counter',
        ),
        migrations.AlterField(
            model_name='profile',
            name='boughted_books',
            field=models.ManyToManyField(blank=True, null=True, to='store.Product'),
        ),
    ]
