# Generated by Django 3.0.2 on 2020-03-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0004_auto_20200315_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boughted_books',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
    ]
