# Generated by Django 3.0 on 2020-02-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('trademark', models.CharField(choices=[('SW', 'SW'), ('SS', 'SS')], max_length=2)),
                ('adress', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hire_date', models.DateField(verbose_name='hire date')),
                ('dismiss_date', models.DateField(blank=True, null=True, verbose_name='dismissing date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('is_superuser', models.BooleanField()),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='working day')),
                ('hours', models.PositiveIntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Shop')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Cost_type')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='day')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comment', models.CharField(max_length=50)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Cost')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Shop')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Staff')),
            ],
        ),
    ]
