# Generated by Django 3.0 on 2020-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200221_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
