# Generated by Django 3.0 on 2020-02-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200221_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
