# Generated by Django 3.0 on 2020-02-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200221_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='comment',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='management.Shop'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='management.Staff'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='adress',
            field=models.CharField(blank=True, default=1, max_length=128),
            preserve_default=False,
        ),
    ]
