# Generated by Django 3.0 on 2020-04-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200222_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Shop'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Staff'),
        ),
    ]
