# Generated by Django 3.0.2 on 2020-03-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ALL', 'ALL'), ('RNSQ', 'Romanesque'), ('GTC', 'Gothic'), ('RNSC', 'Renaissance'), ('BRQ', 'Baroque'), ('RCC', 'Rococo'), ('CLSM', 'Classicism'), ('RMCM', 'Romanticism'), ('ELCM', 'Eclecticism'), ('MDRSM', 'Modernism')], default='ALL', max_length=5)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.jpg', upload_to='posts_pics')),
                ('likes', models.IntegerField(default=0, verbose_name='like')),
                ('dislikes', models.IntegerField(default=0, verbose_name='dislike')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('epoch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Epoch')),
            ],
        ),
    ]
